/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socket.server;

import org.junit.jupiter.api.*;
import socket.client.Client;
import socket.client.Main;
import socket.client.RequestThread;
import socket.server.io.RequestObject;
import socket.server.manager.PrimeCalculationManager;

import javax.annotation.CheckForNull;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    private static InetAddress host;
    private static final int PORT = 9876;
    private static List<Client> list = new ArrayList<>();

    @BeforeAll
    static void initialize() throws IOException {
        Runnable runnable = () -> {
            try {
                new App().startServerAndAcceptRequest();
            } catch (IOException | ClassNotFoundException e) {
                e.printStackTrace();
            }
        };
        Thread serverThread = new Thread(runnable);
        serverThread.start();
        host = InetAddress.getLocalHost();
    }

    @Test
    void singleClientParallelRequest() throws Exception {
        Main ob = new Main();
        ob.singleClientParallelRequest();
    }

    @Test
    void multiClientMultiParallelRequest() throws Exception {
        Main ob = new Main();
        ob.multiClientMultiParallelRequest();
    }
    /*@Test
    void sendRequestWithNonInteger() throws Exception {
        Client client = new Client("client1", "127.0.0.1", 9876,1);
        RequestObject req = new RequestObject();
        HashMap<String, String> hm = new HashMap<>();
        hm.put("n", "NonInteger");
        req.setManagerName("PrimeCalculationManager");
        req.setMethod("findPrimes");
        req.setRequestId("client1-1");
        req.setArgs(hm);
        req.setMessage("request");
        client.sendRequest(req);
        list.add(client);
    }*/

    @AfterAll
    static void release() {
        for (Client c : list)
            c.closeClient();
    }
}
